### ISSUE TITLE
tmux-powerline deprecated

### ISSUE THREAD

**Issue by gabrieljoelc** [JAremko/drop-in#3]
When browsing through the links referenced in the readme, I noticed that `tmux-powerline` has been [deprecated](https://github.com/erikw/tmux-powerline#deprecation-warning) for [5 years ago](https://github.com/erikw/tmux-powerline/commit/9b840c9b906636f7abd43e8316bf701a57500608). It looks like it was deprecated for [`powerline`](https://github.com/powerline/powerline).

Are you planning on moving to `powerline`?

**Comment by JAremko** [comment]
Done :+1:

**Comment by gabrieljoelc** [comment]
For posterity f2b905e6f26351d9320838121cffbfd5a6f8ee38
